import { Extension } from '@tiptap/core'
import { Plugin, PluginKey } from '@tiptap/pm/state'
import type { RichTextPayload } from '../types'

export interface CanvasKeymapOptions {
  onEnterBelow: (initialContent?: RichTextPayload) => void
  onMergeUp: (currentContent?: RichTextPayload) => void
  onFocusPrev: () => void
  onFocusNext: () => void
  onTabPrev: () => void
  onTabNext: () => void
  onDeleteBlock: () => void
}

export const CanvasKeymap = Extension.create<CanvasKeymapOptions>({
  name: 'canvasKeymap',

  addOptions() {
    return {
      onEnterBelow: () => {},
      onMergeUp: (_currentContent?) => {},
      onFocusPrev: () => {},
      onFocusNext: () => {},
      onTabPrev: () => {},
      onTabNext: () => {},
      onDeleteBlock: () => {},
    }
  },

  addProseMirrorPlugins() {
    const { onEnterBelow, onMergeUp, onFocusPrev, onFocusNext, onTabPrev, onTabNext, onDeleteBlock } = this.options

    return [
      new Plugin({
        key: new PluginKey('canvasKeymap'),
        props: {
          handleKeyDown: (view, event) => {
            const { state } = view
            const { selection } = state
            const { $from, $to } = selection

            if ((view as any).composing) {
              return false
            }

            const atStart = view.endOfTextblock('backward', state)
            const atEnd = view.endOfTextblock('forward', state)

            const $pos = state.doc.resolve($from.pos)
            const isInList = $pos.parent.type.name === 'listItem'

            if (event.key === 'Enter' && !event.shiftKey && !isInList) {
              event.preventDefault()

              // If cursor is at the end, just create an empty block below
              if (atEnd) {
                onEnterBelow()
                return true
              }

              // If cursor is in the middle, split the content
              const { $from } = selection

              // Get the parent node (paragraph, heading, etc.) and its type
              const parentNode = $from.parent
              const parentType = parentNode.type

              // Get content after cursor within the parent node
              const afterSlice = state.doc.slice($from.pos, $from.end())

              // Create a new node of the same type (paragraph, heading, etc.) with the after content
              const afterNode = parentType.create(parentNode.attrs, afterSlice.content)

              // Wrap in proper doc structure
              const afterJson = {
                type: 'doc',
                content: [afterNode.toJSON()]
              }

              // Delete content after cursor from current editor
              const deleteTr = state.tr.delete($from.pos, $from.end())
              view.dispatch(deleteTr)

              // Create new block below with the after content
              const afterHtml = ''  // Will be generated by the handler
              onEnterBelow({ json: afterJson, html: afterHtml })
              return true
            }

            if (event.key === 'Backspace' && atStart && $from.sameParent($to)) {
              // Guard against IME composition
              if ((view as any).composing) {
                return false
              }

              event.preventDefault()
              const isEmpty = !state.doc.textContent || state.doc.textContent.trim().length === 0
              if (isEmpty) {
                onDeleteBlock()
              } else {
                // Get current editor content to pass to merge handler
                // This ensures we use the latest typed content, not stale React state
                const currentJson = state.doc.toJSON()
                onMergeUp({ json: currentJson, html: '' })
              }
              return true
            }

            if (event.key === 'ArrowUp' && atStart) {
              event.preventDefault()
              onFocusPrev()
              return true
            }

            if (event.key === 'ArrowDown' && atEnd) {
              event.preventDefault()
              onFocusNext()
              return true
            }

            if (event.key === 'Tab') {
              if (!isInList) {
                event.preventDefault()
                if (event.shiftKey) {
                  onTabPrev()
                } else {
                  onTabNext()
                }
                return true
              }
            }

            return false
          },
        },
      }),
    ]
  },
})
