import { Extension } from '@tiptap/core'
import { Plugin, PluginKey } from '@tiptap/pm/state'
import type { RichTextPayload } from '../types'

export interface CanvasKeymapOptions {
  onEnterBelow: (initialContent?: RichTextPayload) => void
  onMergeUp: (currentContent?: RichTextPayload) => void
  onFocusPrev: () => void
  onFocusNext: () => void
  onTabPrev: () => void
  onTabNext: () => void
  onDeleteBlock: () => void
}

export const CanvasKeymap = Extension.create<CanvasKeymapOptions>({
  name: 'canvasKeymap',

  addOptions() {
    return {
      onEnterBelow: () => {},
      onMergeUp: (_currentContent?) => {},
      onFocusPrev: () => {},
      onFocusNext: () => {},
      onTabPrev: () => {},
      onTabNext: () => {},
      onDeleteBlock: () => {},
    }
  },

  addProseMirrorPlugins() {
    const { onEnterBelow, onMergeUp, onFocusPrev, onFocusNext, onTabPrev, onTabNext, onDeleteBlock } = this.options

    return [
      new Plugin({
        key: new PluginKey('canvasKeymap'),
        props: {
          handleKeyDown: (view, event) => {
            const { state } = view
            const { selection } = state
            const { $from, $to } = selection

            if ((view as any).composing) {
              return false
            }

            const atStart = view.endOfTextblock('backward', state)
            const atEnd = view.endOfTextblock('forward', state)
            const atTopLine = view.endOfTextblock('up', state)
            const atBottomLine = view.endOfTextblock('down', state)

            const $pos = state.doc.resolve($from.pos)
            const isInList = $pos.parent.type.name === 'listItem'

            // Check if user is interacting with any menu or dropdown
            // We check the DOM directly since focus remains on the editor even when menus are open
            const hasSlashMenu = !!document.querySelector('.slash-menu')
            const hasDropdownMenu = !!document.querySelector('[data-radix-popper-content-wrapper]')
            const isMenuOpen = hasSlashMenu || hasDropdownMenu

            // Helper to find ancestor node by name
            const findAncestor = (name: string) => {
              for (let d = $from.depth; d >= 0; d--) {
                const n = $from.node(d)
                if (n.type.name === name) return { node: n, depth: d }
              }
              return null
            }

            // Notion-style list behavior: Enter in empty last item exits list
            const listItem = findAncestor('listItem') || findAncestor('taskItem')

            if (event.key === 'Enter' && !event.shiftKey && !isMenuOpen && listItem) {
              const itemNode = listItem.node
              const isEmptyItem = itemNode.textContent.trim().length === 0
              const listDepth = listItem.depth - 1 // parent is bulletList / orderedList / taskList
              const listNode = listDepth >= 0 ? $from.node(listDepth) : null
              const isLastItem = !!listNode && listNode.lastChild === itemNode

              // Notion-style exit: empty last item → exit list and create new block below
              if (isEmptyItem && isLastItem) {
                event.preventDefault()
                // Just create new block outside list, don't delete the empty item
                // (deleting it can remove the entire block structure)
                onEnterBelow()
                return true
              }

              // otherwise: regular Enter = new list item (TipTap default)
              return false
            }

            if (event.key === 'Enter' && !event.shiftKey && !isInList && !isMenuOpen) {
              event.preventDefault()

              // If cursor is at the end, just create an empty block below
              if (atEnd) {
                onEnterBelow()
                return true
              }

              // If cursor is in the middle, split the content
              const { $from } = selection

              // Get the parent node (paragraph, heading, etc.) and its type
              const parentNode = $from.parent
              const parentType = parentNode.type

              // Get content after cursor within the parent node
              const afterSlice = state.doc.slice($from.pos, $from.end())

              // Create a new node of the same type (paragraph, heading, etc.) with the after content
              const afterNode = parentType.create(parentNode.attrs, afterSlice.content)

              // Wrap in proper doc structure
              const afterJson = {
                type: 'doc',
                content: [afterNode.toJSON()]
              }

              // Delete content after cursor from current editor
              const deleteTr = state.tr.delete($from.pos, $from.end())
              view.dispatch(deleteTr)

              // Create new block below with the after content
              const afterHtml = ''  // Will be generated by the handler
              onEnterBelow({ json: afterJson, html: afterHtml })
              return true
            }

            if (event.key === 'Backspace' && $from.pos === 1 && $from.sameParent($to)) {
              // Guard against IME composition
              if ((view as any).composing) {
                return false
              }

              event.preventDefault()
              const isEmpty = !state.doc.textContent || state.doc.textContent.trim().length === 0
              if (isEmpty) {
                onDeleteBlock()
              } else {
                // Get current editor content to pass to merge handler
                // This ensures we use the latest typed content, not stale React state
                const currentJson = state.doc.toJSON()
                onMergeUp({ json: currentJson, html: '' })
              }
              return true
            }

            // Jump blocks when at top/bottom line of current block
            if (event.key === 'ArrowUp' && atTopLine && !isMenuOpen) {
              // If in a list, only jump if we're at the first item
              if (listItem) {
                const listDepth = listItem.depth - 1
                const listNode = listDepth >= 0 ? $from.node(listDepth) : null
                const isFirstItem = !!listNode && listNode.firstChild === listItem.node
                if (!isFirstItem) {
                  return false // Let TipTap navigate to previous list item
                }
              }

              event.preventDefault()
              onFocusPrev()
              return true
            }

            if (event.key === 'ArrowDown' && atBottomLine && !isMenuOpen) {
              // If in a list, only jump if we're at the last item
              if (listItem) {
                const listDepth = listItem.depth - 1
                const listNode = listDepth >= 0 ? $from.node(listDepth) : null
                const isLastItem = !!listNode && listNode.lastChild === listItem.node
                if (!isLastItem) {
                  return false // Let TipTap navigate to next list item
                }
              }

              event.preventDefault()
              onFocusNext()
              return true
            }

            if (event.key === 'Tab') {
              if (!isInList) {
                event.preventDefault()
                if (event.shiftKey) {
                  onTabPrev()
                } else {
                  onTabNext()
                }
                return true
              }
            }

            return false
          },
        },
      }),
    ]
  },
})
